### ISSUE TITLE
If I "enable" core dumps with chef-os-hardening, am I really fully enabling core dumps?

### ISSUE THREAD

**Issue by boldandbusted** [dev-sec/chef-os-hardening#105]
We have a need to enable core dumps on production to assist our developers in troubleshooting "interesting" problems. While I see that chef-os-hardening has facilities to disable core files, is the converse true?

Basically, I'll want to do this: http://www.kibinlabs.com/re-enabling-core-dumps-redhat-7/

Thanks! :)

**Comment by artem-sidorenko** [comment]
@boldandbusted sorry for huge delay :) This should be resolved by https://github.com/dev-sec/chef-os-hardening/pull/171. I'm closing this, feel free to reopen if needed
