### ISSUE TITLE
Umask

### ISSUE THREAD

**Issue by runningman84** [dev-sec/chef-os-hardening#107]
If I use the os-hardening framework, several cookbooks like rabbitmq and sensu(-plugins) fail to install.

It looks like chef itself uses umask 0007 for all operations. If I install any gem it is not readable by others anymore. How would you solve these issues?

**Comment by foonix** [comment]
The setting originates from [NSA's guidelines](https://www.nsa.gov/ia/_files/os/redhat/NSA_RHEL_5_GUIDE_v4.2.pdf), the description of which provides some guidance.  

> The  settings  file /etc/sysconfig/init contains  settings  which  apply  to  all  processes  started  at  boot  time.
> The  system  umask  must  be  set  to  at  least 022,  or  daemon  processes  may  create  world-writable  files.   The more restrictive setting 027 protects files, including temporary files and log files, from unauthorized reading by unprivileged users on the system.
> If a particular daemon needs a less restrictive umask, consider editing the startup script or sysconfig file of that daemon to make a specific exception.

From what I gather, the general idea is to force the issue of deciding which users should have access to which files.  Sorting through these issues will make the system more secure by preventing unrelated services from reading each other's data.

- If one user needs access to another user's files, they should be members of a mutual group and the files' group owner should be that group.
- If something actually needs to be globally readable, it should be explicitly set so.
- As suggested, if a daemon can't operate properly, set its umask on startup.  Chef its self probably falls into this category.  It might be worth treating the reason for the installation failures as a bug, however.

**Comment by artem-sidorenko** [comment]
@runningman84 sorry for a very late answer. @foonix answer it right, if this umask is 'too strong' for you our you don't want to have it this way: you can set/change the according attribute of this cookbook.

I'm closing this issue, feel free to reopen it or create another one if you see any discussion need or have any improvement ideas. We try to react a bit better than in the past and to get this cookbooks actively maintained.
