### ISSUE TITLE
attributes need to be localized to the `node['chef-os-hardening']` namespace

### ISSUE THREAD

**Issue by lamont-granquist** [dev-sec/chef-os-hardening#113]
Issue to track #88 in case that PR gets closed without getting merged because its out of date now.

The way this cookbook stomps on attributes namespaces violates long-standing policy regarding cookbook attribute namespacing (that predates our RFC process by many years so I don't have a convenient authoritative URL to point at).

See https://github.com/chef/chef/issues/4849 for example issue getting cut against core chef which we've closed pointing to this cookbook needing to get fixed.

**Comment by chris-rock** [comment]
This is solved in master and version 2.0.0-beta
