### ISSUE TITLE
login.defs.erb contains a non-ASCII character which causes a knife cookbook upload failure

### ISSUE THREAD

**Issue by gregorkistler** [dev-sec/chef-os-hardening#122]
_$ knife cookbook upload os-hardening_
ERROR: ArgumentError: invalid byte sequence in US-ASCII

_$ grep --color='auto' -P -n "[\x80-\xFF]" cookbooks/*/templates/*/*_
cookbooks/os-hardening/templates/default/login.defs.erb:95:# If set to yes, userdel will remove the user**??**s group if it contains no more members, and useradd will create by default a group with the name of the user.

Original content:
`# If set to yes, userdel will remove the user´s group if it contains no more members, and useradd will create by default a group with the name of the user.`

Could you please use a ' instead of a ´ ?

**Comment by atomic111** [comment]
Hi @gregorkistler,
thanks for finding this. i will fix this in the next couple weeks.

**Comment by atomic111** [comment]
fixed with #124 @gregorkistler 

can we close the issue

**Comment by gregorkistler** [comment]
@atomic111 yep, can be closed, thank you.
