### ISSUE TITLE
auditd package is not installed

### ISSUE THREAD

**Issue by chris-rock** [dev-sec/chef-os-hardening#145]
According to https://github.com/dev-sec/linux-baseline/blob/master/controls/package_spec.rb#L79-L103 we need to add the package `auditd`

**Comment by grdnrio** [comment]
+1 - required for 100% coverage of the baseline profile

**Comment by artem-sidorenko** [comment]
#158 was not complete, audit has different package names on different distros. I'll provide another PR

**Comment by artem-sidorenko** [comment]
#161 should resolve this
