### ISSUE TITLE
PAM conflicts between os-hardening and sssd_ldap cookbooks

### ISSUE THREAD

**Issue by MattMencel** [dev-sec/chef-os-hardening#156]
I use the sssd_ldap cookbook on my nodes which uses authconfig to modify PAM settings.  Now I've started testing this cookbook and see that it's overriding the modifications the sssd_ldap cookbook has made.  I can still SSH into the node using my LDAP creds, but attempting to use sudo fails with a bad or incorrect password warning.

I'm willing to create a pull request, but I'm not sure which direction to go.

- Detect if sssd_ldap is in use and add those modifications to the rhel_system_auth.erb template in this cookbook?
- Create an optional attribute to disable the pam modifications in this cookbook and just make the pam modifications in the sssd_ldap cookbook?
- Some other option?

On CentOS 7 the ldap_sssd cookbook creates /etc/pam.d/system-auth like this:
```
auth        required      pam_env.so
auth        [default=1 success=ok] pam_localuser.so
auth        [success=done ignore=ignore default=die] pam_unix.so nullok try_first_pass
auth        requisite     pam_succeed_if.so uid >= 1000 quiet_success
auth        sufficient    pam_sss.so forward_pass
auth        required      pam_deny.so

account     required      pam_unix.so
account     sufficient    pam_localuser.so
account     sufficient    pam_succeed_if.so uid < 1000 quiet
account     [default=bad success=ok user_unknown=ignore] pam_sss.so
account     required      pam_permit.so

password    requisite     pam_pwquality.so try_first_pass local_users_only retry=3 authtok_type=
password    sufficient    pam_unix.so sha512 shadow nullok try_first_pass use_authtok
password    sufficient    pam_sss.so use_authtok
password    required      pam_deny.so

session     optional      pam_keyinit.so revoke
session     required      pam_limits.so
-session     optional      pam_systemd.so
session     [success=1 default=ignore] pam_succeed_if.so service in crond quiet use_uid
session     required      pam_unix.so
session     optional      pam_sss.so
```

I've done some testing on CentOS 7, and adding the additional 'pam_sss.so' lines to the the template in os-hardening seems to fix my sudo issue.

**Comment by artem-sidorenko** [comment]
For me the most simple and simple way looks like introduction of new attribute `['os-hardening']['auth']['pam']['enable']`. Per default its `true`, if switched to `false` - the entire `pam` recipe is not executed.

@MattMencel would this solve your problem?

@chris-rock @atomic111 opinions?

**Comment by MattMencel** [comment]
Works for me if it works for you.  I'll try to get a PR in on it in the next day or so.

**Comment by artem-sidorenko** [comment]
@MattMencel not sure if this issue is still relevant. I'm closing it, feel free to reopen if needed
