### ISSUE TITLE
Question about the default for client_alive_interval

### ISSUE THREAD

**Issue by iennae** [dev-sec/chef-os-hardening#185]
The default for   server['client_alive_interval']    = 600     # 10min is currently 600. The default value fails the Ensure SSH Idle Timeout Interval is configured test:

  ×  xccdf_org.cisecurity.benchmarks_rule_5.2.13_Ensure_SSH_Idle_Timeout_Interval_is_configured: Ensure SSH Idle Timeout Interval is configured (1 failed)
     ✔  File /etc/ssh/sshd_config content should match /^\s*ClientAliveInterval\s+(\S+)\s*(?:#.*)?$/
     ×  600 should cmp <= 300

     expected it to be <= 300
          got: 600

     (compared using `cmp` matcher)

If the expected value is less than equal to 300, should the default be set to 300? I know I can set the attribute specifically to the cookbook, just wanted to check in on this. This might be something that also needs to be evaluated with the profile as the description for the benchmark is just that it's configured but the test is based on the recommended setting of 300.

**Comment by artem-sidorenko** [comment]
@iennae thanks for raising this!

Isn't this related to [chef-ssh-hardening](https://github.com/dev-sec/chef-ssh-hardening) ? Or even [ssh-baseline](https://github.com/dev-sec/ssh-baseline/blob/master/controls/ssh_spec.rb)?

I'm happy to change this, may I ask you to create PR(s) to the baseline and/or cookbook?

**Comment by iennae** [comment]
Ahh, you're right. I totally put this in the wrong cookbook. I'm happy to create a PR just wanted to get the feels before I did.
