### ISSUE TITLE
Migration to the new major sysctl cookbook version

### ISSUE THREAD

**Issue by artem-sidorenko** [dev-sec/chef-os-hardening#198]
sysctl 1.0.0 does not have recipes anymore, everything is done via custom resources. We need to reflect this within chef-os-hardening

**Comment by Veraticus** [comment]
I took a stab at this on my fork at: https://github.com/symondsandson/chef-os-hardening/commit/c59808627cd53a58f04f10f249a686a823be8a5c

It works for my servers, though I haven't tried your CI so no idea if it'll integrate.

**Comment by artem-sidorenko** [comment]
Resolved via #210
