### ISSUE TITLE
Make a new release?

### ISSUE THREAD

**Issue by mattlqx** [dev-sec/chef-os-hardening#233]
Can we get another release please? It's been about 7 months and a couple things have been added. Including my #215 :) Thanks!

**Comment by eyespies** [comment]
I would like to submit a quick PR before this is done, but if mine cannot be reviewed / approved quick enough, then mine can be added later.

**Comment by eyespies** [comment]
I've opened #234 and will be submitting a PR shortly.

**Comment by artem-sidorenko** [comment]
@mattlqx 3.2.0 is released. Thank for heads up and sorry for such delay.

@eyespies I'll review #234 in the next time, after it gets merged I'll release the next minor
