### ISSUE TITLE
Support for RHEL 8 / Rocky Linux 8

### ISSUE THREAD

**Issue by krayjay** [dev-sec/chef-os-hardening#279]
**Is your feature request related to a problem? Please describe.**
I can run this cookbook in Rocky Linux 8, but the compliance report shows the scan results as:
19 passed controls, 5 failed controls, and 44 were skipped (due to thinking `/etc/ssh/sshd` file does not exist, yet it does)

**Describe the solution you'd like**
Support for RHEL 8 since 9 has been out for a little bit and 8 still isn't supported. RHEL = Rocky Linux so fixing both would be phenomenal.

**Describe alternatives you've considered**
Ansible if the Chef community can't keep these popular cookbooks updated, unfortunately.

**Comment by schurzi** [comment]
Thank you for this input. As you observed in the alternatives section, we currently put more effort in maintaining our Ansible implementation. We also recognize the popularity of the chef cookbooks, but currently we lack maintainer time to keep everything equally up-to-date.

A sidenote to your experience with the compliance profile. If this many controls are skipped you should try running it as root user.

**Comment by artem-sidorenko** [comment]
@krayjay I added the CI tests for EL 8-9 linux distro, including rocky linux 8. As far I can see everything works and tests are passing, even on the old chef-os-hardening release 4.0.0. Is there anything I miss or any specific problem which needs to be fixed?

**Comment by artem-sidorenko** [comment]
I'm closing this issue, feel free to reopen if needed
