### ISSUE TITLE
Actually log martians?

### ISSUE THREAD

**Issue by patcon** [dev-sec/chef-os-hardening#89]
Comment seems to indicate we want to log, but setting is not to:

https://github.com/hardening-io/chef-os-hardening/blob/b5a0a3e34776bd93d6c553f133c46527ebd2d965/attributes/sysctl.rb#L125

This slide also seems to indicate that we want to log:
http://www.slideshare.net/myowntelco/centos-linux-server-hardening#18

**Comment by chris-rock** [comment]
Hi @patcon Thanks for reporting this. Yes, we should log it by default. See also [CIS Benchmark reference in section 4.2.4 Log Suspicious Packets (Scored)](https://benchmarks.cisecurity.org/tools2/linux/CIS_CentOS_Linux_7_Benchmark_v1.0.0.pdf)

sysctl should have the following values by default:
```
net.ipv4.conf.all.log_martians=1
net.ipv4.conf.default.log_martians=1
```
