### ISSUE TITLE
`execute[update-pam]` copied resource fails on chef-client 12.5

### ISSUE THREAD

**Issue by patcon** [dev-sec/chef-os-hardening#95]
Failure log output: https://gist.github.com/patcon/32e942c560dee6727f43

Line in question: https://github.com/hardening-io/chef-os-hardening/blob/master/recipes/pam.rb#L96

I assume this has something to do with the fact that resource copying has been deprecated to awhile, and the behaviour this resource-use pattern depends on is no longer how Chef works.

We could fix this by instead adding this to one of the resources that runs during this condition:

``` rb
some_resource 'foo' do
  some_key some_value
  notifies :run, 'execute[update-pam]', :immediately
end
```

**Comment by cmjosh** [comment]
I just hit this on a node running chef-client 12.5.1 myself. This workaround using chef_rewind appears to work (on Ubuntu 14.04) for me until a proper fix is implemented:

```
chef_gem 'chef-rewind'
require 'chef/rewind'

rewind 'execute[update-pam]' do
	command 'pam-auth-update --package'
end
```

**Comment by mikemoate** [comment]
@patcon are you working on a fix for this issue? If not, I'd be happy to take a look.

**Comment by patcon** [comment]
Hm. Go figure. I didn't remember solving it, but I'm not hitting the issue anymore, so I checked, and I guess I had an unsubmitted bugfix :) #100

**Comment by artem-sidorenko** [comment]
It looks like this issue is not happening anymore, I'm closing it. Feel free to reopen if needed
